"""Helper script to write notebook 08 Audio TTS. Delete after use."""
import json

nb = {
 "cells": [
  {"cell_type": "markdown", "metadata": {}, "source": [
    "# Notebook 08: Audio - Text-to-Speech (TTS)\n",
    "\n",
    "## Learning Objectives\n",
    "\n",
    "In this notebook, you will learn:\n",
    "- How to generate natural-sounding speech from text\n",
    "- How SpeechT5 works as an encoder-decoder model for TTS\n",
    "- How speaker embeddings control voice characteristics\n",
    "- How a vocoder (HiFi-GAN) converts spectrograms to waveforms\n",
    "- How to generate speech with different voices\n",
    "- How to save and play generated audio files"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Prerequisites\n",
    "\n",
    "### Hardware Requirements\n",
    "\n",
    "| Model Option | Model Name | Size | Min RAM | Recommended Setup | Notes |\n",
    "|--------------|------------|------|---------|-------------------|-------|\n",
    "| **CPU/GPU** | microsoft/speecht5_tts | 200MB | 4GB | Any CPU | Works well on CPU |\n",
    "| **Vocoder** | microsoft/speecht5_hifigan | 50MB | 4GB | Same as above | Required companion model |\n",
    "\n",
    "### Software Requirements\n",
    "- Python 3.10+\n",
    "- Libraries: `transformers`, `torch`, `soundfile`, `datasets`\n",
    "- Total download on first run: ~350MB (model + vocoder + speaker embeddings)"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Expected Behaviors\n",
    "\n",
    "**First Time Running**:\n",
    "- SpeechT5 TTS model: ~200MB download\n",
    "- HiFi-GAN vocoder: ~50MB download\n",
    "- Speaker embeddings dataset: ~100MB download\n",
    "- Total: ~350MB, cached after first run\n",
    "\n",
    "**Audio Output**:\n",
    "- WAV format at 16kHz sample rate\n",
    "- Typical sentence generates 1-5 seconds of audio\n",
    "- Quality is clear and natural for English text\n",
    "\n",
    "**Performance**:\n",
    "- CPU: 1-3 seconds per sentence\n",
    "- GPU: <1 second per sentence\n",
    "- Longer text takes proportionally longer\n",
    "\n",
    "**Limitations**:\n",
    "- Best with English text (SpeechT5 is English-focused)\n",
    "- Maximum ~600 characters per generation\n",
    "- No emotion or prosody control beyond speaker embedding"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Overview\n",
    "\n",
    "**Text-to-Speech (TTS)** converts written text into spoken audio.\n",
    "\n",
    "**Use Cases**: Screen readers, virtual assistants, audiobook generation, accessibility tools, language learning, automated announcements.\n",
    "\n",
    "### SpeechT5 Architecture\n",
    "\n",
    "SpeechT5 uses a unified encoder-decoder framework that handles both speech and text:\n",
    "\n",
    "1. **Text Encoder**: Converts input text into hidden representations\n",
    "2. **Speech Decoder**: Generates a mel-spectrogram conditioned on text features + speaker embedding\n",
    "3. **Vocoder (HiFi-GAN)**: Converts the mel-spectrogram into a raw audio waveform\n",
    "\n",
    "The **speaker embedding** is a vector that captures voice characteristics (pitch, timbre, speaking style). By swapping embeddings, you can generate the same text in different voices.\n",
    "\n",
    "### TTS Pipeline\n",
    "\n",
    "```\n",
    "Text -> [Text Encoder] -> [Speech Decoder + Speaker Embedding] -> Mel Spectrogram -> [Vocoder] -> Audio Waveform\n",
    "```"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Setup and Installation"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "import sys, time, random, warnings\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import torch\n",
    "import transformers\n",
    "from transformers import (\n",
    "    SpeechT5Processor,\n",
    "    SpeechT5ForTextToSpeech,\n",
    "    SpeechT5HifiGan,\n",
    "    set_seed,\n",
    ")\n",
    "from datasets import load_dataset\n",
    "import soundfile as sf\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "SEED = 1103\n",
    "random.seed(SEED)\n",
    "np.random.seed(SEED)\n",
    "torch.manual_seed(SEED)\n",
    "set_seed(SEED)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed_all(SEED)\n",
    "\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "\n",
    "print(f\"Python: {sys.version.split()[0]}\")\n",
    "print(f\"PyTorch: {torch.__version__}\")\n",
    "print(f\"Transformers: {transformers.__version__}\")\n",
    "print(f\"Device: {device}\")"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Model Selection and Loading\n",
    "\n",
    "SpeechT5 TTS requires three components: the processor (text tokenization), the model (spectrogram generation), and the vocoder (waveform synthesis)."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "MODEL_NAME = \"microsoft/speecht5_tts\"  # 200MB\n",
    "VOCODER_NAME = \"microsoft/speecht5_hifigan\"  # 50MB\n",
    "SAMPLE_RATE = 16000  # SpeechT5 outputs 16kHz audio\n",
    "\n",
    "try:\n",
    "    print(f\"Loading TTS model: {MODEL_NAME}\")\n",
    "    processor = SpeechT5Processor.from_pretrained(MODEL_NAME)\n",
    "    model = SpeechT5ForTextToSpeech.from_pretrained(MODEL_NAME)\n",
    "    vocoder = SpeechT5HifiGan.from_pretrained(VOCODER_NAME)\n",
    "\n",
    "    model.to(device)\n",
    "    vocoder.to(device)\n",
    "\n",
    "    print(f\"Model loaded on {device}.\")\n",
    "    print(f\"Vocoder: {VOCODER_NAME}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error loading model: {e}\")\n",
    "    print(\"Ensure you have internet access and sufficient disk space (~250MB).\")"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "### Load Speaker Embeddings\n",
    "\n",
    "Speaker embeddings are pre-computed x-vectors from the CMU Arctic dataset. Each vector encodes a different speaker's voice characteristics."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "try:\n",
    "    embeddings_dataset = load_dataset(\"Matthijs/cmu-arctic-xvectors\", split=\"validation\")\n",
    "    DEFAULT_SPEAKER_IDX = 7306\n",
    "    speaker_embeddings = torch.tensor(\n",
    "        embeddings_dataset[DEFAULT_SPEAKER_IDX][\"xvector\"]\n",
    "    ).unsqueeze(0).to(device)\n",
    "\n",
    "    print(f\"Speaker embeddings loaded: {len(embeddings_dataset)} voices available\")\n",
    "    print(f\"Default speaker index: {DEFAULT_SPEAKER_IDX}\")\n",
    "    print(f\"Embedding shape: {speaker_embeddings.shape}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error loading speaker embeddings: {e}\")"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Method 1: Basic Text-to-Speech\n",
    "\n",
    "The core TTS function takes text input, processes it through the model, and produces a waveform via the vocoder."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def text_to_speech(\n",
    "    text: str,\n",
    "    output_file: str | None = None,\n",
    "    speaker_embedding: torch.Tensor | None = None,\n",
    ") -> np.ndarray:\n",
    "    \"\"\"Convert text to speech audio.\n",
    "\n",
    "    Args:\n",
    "        text: Input text to synthesize.\n",
    "        output_file: Optional path to save WAV file.\n",
    "        speaker_embedding: Optional speaker embedding tensor. Uses default if None.\n",
    "\n",
    "    Returns:\n",
    "        Audio waveform as numpy array (16kHz).\n",
    "    \"\"\"\n",
    "    if speaker_embedding is None:\n",
    "        speaker_embedding = speaker_embeddings\n",
    "\n",
    "    inputs = processor(text=text, return_tensors=\"pt\").to(device)\n",
    "\n",
    "    with torch.no_grad():\n",
    "        speech = model.generate_speech(\n",
    "            inputs[\"input_ids\"],\n",
    "            speaker_embedding,\n",
    "            vocoder=vocoder,\n",
    "        )\n",
    "\n",
    "    audio = speech.cpu().numpy()\n",
    "\n",
    "    if output_file:\n",
    "        sf.write(output_file, audio, SAMPLE_RATE)\n",
    "        print(f\"Saved: {output_file} ({len(audio)/SAMPLE_RATE:.2f}s)\")\n",
    "\n",
    "    return audio"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "# Generate a simple greeting\n",
    "text = \"Hello, welcome to the HuggingFace tutorial on text to speech!\"\n",
    "\n",
    "start = time.perf_counter()\n",
    "audio = text_to_speech(text, \"hello.wav\")\n",
    "elapsed = time.perf_counter() - start\n",
    "\n",
    "duration = len(audio) / SAMPLE_RATE\n",
    "print(f\"Generated {duration:.2f}s of audio in {elapsed:.2f}s\")\n",
    "print(f\"Realtime factor: {duration / elapsed:.1f}x\")"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "### Visualize the Waveform\n",
    "\n",
    "Let's look at the raw audio waveform to understand what was generated."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def plot_waveform(audio: np.ndarray, title: str = \"Waveform\") -> None:\n",
    "    \"\"\"Plot an audio waveform.\n",
    "\n",
    "    Args:\n",
    "        audio: Audio samples as numpy array.\n",
    "        title: Plot title.\n",
    "    \"\"\"\n",
    "    duration = len(audio) / SAMPLE_RATE\n",
    "    time_axis = np.linspace(0, duration, len(audio))\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(10, 3))\n",
    "    ax.plot(time_axis, audio, linewidth=0.5)\n",
    "    ax.set_xlabel(\"Time (s)\")\n",
    "    ax.set_ylabel(\"Amplitude\")\n",
    "    ax.set_title(title, fontsize=12, fontweight=\"bold\")\n",
    "    ax.set_xlim(0, duration)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "plot_waveform(audio, f\"Generated Speech: '{text[:40]}...'\")"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Method 2: Generating Multiple Phrases\n",
    "\n",
    "Let's batch-generate speech for several phrases and compare audio characteristics."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def generate_multiple(\n",
    "    phrases: list[str], output_prefix: str = \"speech\"\n",
    ") -> pd.DataFrame:\n",
    "    \"\"\"Generate speech for multiple phrases.\n",
    "\n",
    "    Args:\n",
    "        phrases: List of text strings to synthesize.\n",
    "        output_prefix: Prefix for output WAV filenames.\n",
    "\n",
    "    Returns:\n",
    "        DataFrame with phrase, duration, generation time, and file path.\n",
    "    \"\"\"\n",
    "    rows = []\n",
    "    for i, phrase in enumerate(phrases, 1):\n",
    "        output_file = f\"{output_prefix}_{i:02d}.wav\"\n",
    "        start = time.perf_counter()\n",
    "        audio = text_to_speech(phrase, output_file)\n",
    "        elapsed = time.perf_counter() - start\n",
    "        duration = len(audio) / SAMPLE_RATE\n",
    "\n",
    "        rows.append({\n",
    "            \"#\": i,\n",
    "            \"Text\": phrase[:50],\n",
    "            \"Duration (s)\": f\"{duration:.2f}\",\n",
    "            \"Gen Time (s)\": f\"{elapsed:.2f}\",\n",
    "            \"File\": output_file,\n",
    "        })\n",
    "\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "phrases = [\n",
    "    \"Artificial intelligence is transforming the world.\",\n",
    "    \"Machine learning models can now understand and generate speech.\",\n",
    "    \"This technology has many practical applications.\",\n",
    "]\n",
    "\n",
    "print(\"Batch Speech Generation\")\n",
    "generate_multiple(phrases)"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Method 3: Different Speaker Voices\n",
    "\n",
    "By changing the speaker embedding, we can generate the same text in different voices. Each embedding in the CMU Arctic dataset corresponds to a different speaker."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def generate_with_voices(\n",
    "    text: str, speaker_indices: list[int] | None = None\n",
    ") -> pd.DataFrame:\n",
    "    \"\"\"Generate speech with different speaker voices.\n",
    "\n",
    "    Args:\n",
    "        text: Text to synthesize.\n",
    "        speaker_indices: List of indices into the speaker embeddings dataset.\n",
    "\n",
    "    Returns:\n",
    "        DataFrame with speaker index, duration, and file path.\n",
    "    \"\"\"\n",
    "    if speaker_indices is None:\n",
    "        speaker_indices = [0, 1000, 3000, 5000, 7306]\n",
    "\n",
    "    rows = []\n",
    "    for idx in speaker_indices:\n",
    "        if idx >= len(embeddings_dataset):\n",
    "            continue\n",
    "\n",
    "        spk_emb = torch.tensor(\n",
    "            embeddings_dataset[idx][\"xvector\"]\n",
    "        ).unsqueeze(0).to(device)\n",
    "\n",
    "        output_file = f\"voice_{idx}.wav\"\n",
    "        start = time.perf_counter()\n",
    "        audio = text_to_speech(text, output_file, speaker_embedding=spk_emb)\n",
    "        elapsed = time.perf_counter() - start\n",
    "        duration = len(audio) / SAMPLE_RATE\n",
    "\n",
    "        rows.append({\n",
    "            \"Speaker Index\": idx,\n",
    "            \"Duration (s)\": f\"{duration:.2f}\",\n",
    "            \"Gen Time (s)\": f\"{elapsed:.2f}\",\n",
    "            \"File\": output_file,\n",
    "        })\n",
    "\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "print(\"Different Speaker Voices\")\n",
    "print(f\"Text: 'Hello, this is a voice test.'\\n\")\n",
    "generate_with_voices(\"Hello, this is a voice test.\")"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "Each speaker index produces a different voice. In practice, you would select the voice that best fits your application (e.g., male/female, formal/casual).\n",
    "\n",
    "## Practical Applications"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "### Application 1: Long Text Processing\n",
    "\n",
    "SpeechT5 has a maximum input length. For longer text, we split into sentences and concatenate the audio."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def synthesize_long_text(\n",
    "    text: str, output_file: str = \"long_output.wav\"\n",
    ") -> pd.DataFrame:\n",
    "    \"\"\"Synthesize speech for long text by splitting into sentences.\n",
    "\n",
    "    Args:\n",
    "        text: Long input text to synthesize.\n",
    "        output_file: Path to save the concatenated WAV file.\n",
    "\n",
    "    Returns:\n",
    "        DataFrame with per-sentence timing information.\n",
    "    \"\"\"\n",
    "    # Split on sentence boundaries\n",
    "    import re\n",
    "    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]\n",
    "\n",
    "    rows = []\n",
    "    audio_segments = []\n",
    "\n",
    "    for i, sentence in enumerate(sentences, 1):\n",
    "        # Add period back for natural prosody\n",
    "        sentence_with_punct = sentence + \".\"\n",
    "        start = time.perf_counter()\n",
    "        try:\n",
    "            audio = text_to_speech(sentence_with_punct)\n",
    "            elapsed = time.perf_counter() - start\n",
    "            audio_segments.append(audio)\n",
    "            rows.append({\n",
    "                \"#\": i,\n",
    "                \"Sentence\": sentence[:40],\n",
    "                \"Duration (s)\": f\"{len(audio)/SAMPLE_RATE:.2f}\",\n",
    "                \"Gen Time (s)\": f\"{elapsed:.2f}\",\n",
    "            })\n",
    "        except Exception as e:\n",
    "            rows.append({\"#\": i, \"Sentence\": sentence[:40], \"Duration (s)\": \"Error\", \"Gen Time (s)\": str(e)[:30]})\n",
    "\n",
    "    if audio_segments:\n",
    "        # Add short silence between sentences\n",
    "        silence = np.zeros(int(SAMPLE_RATE * 0.3), dtype=np.float32)\n",
    "        full_audio = np.concatenate(\n",
    "            [seg for pair in zip(audio_segments, [silence] * len(audio_segments)) for seg in pair][:-1]\n",
    "        )\n",
    "        sf.write(output_file, full_audio, SAMPLE_RATE)\n",
    "        print(f\"Full audio saved: {output_file} ({len(full_audio)/SAMPLE_RATE:.2f}s total)\")\n",
    "\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "long_text = (\n",
    "    \"The history of artificial intelligence began in the 1950s. \"\n",
    "    \"Early researchers believed machines could think like humans. \"\n",
    "    \"Today, AI can understand language and generate speech.\"\n",
    ")\n",
    "\n",
    "print(\"Long Text Synthesis\")\n",
    "synthesize_long_text(long_text)"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "### Application 2: Pronunciation and Prosody Analysis\n",
    "\n",
    "Let's test how punctuation and text formatting affect the generated speech."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def compare_prosody(text_variants: list[tuple[str, str]]) -> pd.DataFrame:\n",
    "    \"\"\"Compare speech generation for different text formulations.\n",
    "\n",
    "    Args:\n",
    "        text_variants: List of (description, text) tuples.\n",
    "\n",
    "    Returns:\n",
    "        DataFrame with description, text, duration, and file.\n",
    "    \"\"\"\n",
    "    rows = []\n",
    "    for desc, text in text_variants:\n",
    "        output = f\"prosody_{desc.lower().replace(' ', '_')}.wav\"\n",
    "        audio = text_to_speech(text, output)\n",
    "        duration = len(audio) / SAMPLE_RATE\n",
    "        rows.append({\n",
    "            \"Variant\": desc,\n",
    "            \"Text\": text,\n",
    "            \"Duration (s)\": f\"{duration:.2f}\",\n",
    "            \"File\": output,\n",
    "        })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "variants = [\n",
    "    (\"Statement\", \"The weather is nice today.\"),\n",
    "    (\"Question\", \"Is the weather nice today?\"),\n",
    "    (\"Exclamation\", \"The weather is nice today!\"),\n",
    "    (\"With comma\", \"The weather, surprisingly, is nice today.\"),\n",
    "    (\"Short\", \"Hello.\"),\n",
    "    (\"Numbers\", \"There are 42 students in the class.\"),\n",
    "]\n",
    "\n",
    "print(\"Prosody Comparison\")\n",
    "compare_prosody(variants)"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Performance Benchmarking\n",
    "\n",
    "Let's measure generation speed for different text lengths."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def benchmark_tts(n_runs: int = 5) -> pd.DataFrame:\n",
    "    \"\"\"Benchmark TTS generation speed for different text lengths.\n",
    "\n",
    "    Args:\n",
    "        n_runs: Number of runs to average per text.\n",
    "\n",
    "    Returns:\n",
    "        DataFrame with text length, generation time, audio duration, and realtime factor.\n",
    "    \"\"\"\n",
    "    test_texts = [\n",
    "        (\"Short\", \"Hello world.\"),\n",
    "        (\"Medium\", \"The quick brown fox jumps over the lazy dog near the river.\"),\n",
    "        (\"Long\", \"Artificial intelligence and machine learning are transforming industries around the world with new capabilities.\"),\n",
    "    ]\n",
    "\n",
    "    rows = []\n",
    "    for label, text in test_texts:\n",
    "        times = []\n",
    "        for _ in range(n_runs):\n",
    "            start = time.perf_counter()\n",
    "            audio = text_to_speech(text)\n",
    "            times.append(time.perf_counter() - start)\n",
    "\n",
    "        mean_time = np.mean(times)\n",
    "        duration = len(audio) / SAMPLE_RATE\n",
    "\n",
    "        rows.append({\n",
    "            \"Text Length\": label,\n",
    "            \"Characters\": len(text),\n",
    "            \"Audio (s)\": f\"{duration:.2f}\",\n",
    "            \"Gen Time (ms)\": f\"{mean_time * 1000:.1f}\",\n",
    "            \"Realtime Factor\": f\"{duration / mean_time:.1f}x\",\n",
    "        })\n",
    "\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "print(f\"TTS Benchmark ({device})\")\n",
    "benchmark_tts()"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Error Analysis\n",
    "\n",
    "Let's test TTS on challenging inputs to understand its limitations."
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def analyze_failure_modes() -> pd.DataFrame:\n",
    "    \"\"\"Test TTS on challenging inputs.\n",
    "\n",
    "    Returns:\n",
    "        DataFrame with test case, input text, and result.\n",
    "    \"\"\"\n",
    "    test_cases = [\n",
    "        (\"Normal\", \"Hello, how are you?\"),\n",
    "        (\"All caps\", \"THIS IS VERY IMPORTANT!\"),\n",
    "        (\"Abbreviations\", \"Dr. Smith from the U.S.A. called.\"),\n",
    "        (\"Numbers\", \"The year 2024 had 365 days.\"),\n",
    "        (\"Special chars\", \"Email me at user@example.com.\"),\n",
    "        (\"Single word\", \"Hello.\"),\n",
    "        (\"Non-English\", \"Bonjour, comment allez-vous?\"),\n",
    "    ]\n",
    "\n",
    "    rows = []\n",
    "    for category, text in test_cases:\n",
    "        try:\n",
    "            start = time.perf_counter()\n",
    "            audio = text_to_speech(text)\n",
    "            elapsed = time.perf_counter() - start\n",
    "            duration = len(audio) / SAMPLE_RATE\n",
    "            rows.append({\n",
    "                \"Category\": category,\n",
    "                \"Input\": text,\n",
    "                \"Duration (s)\": f\"{duration:.2f}\",\n",
    "                \"Status\": \"OK\",\n",
    "            })\n",
    "        except Exception as e:\n",
    "            rows.append({\n",
    "                \"Category\": category,\n",
    "                \"Input\": text,\n",
    "                \"Duration (s)\": \"N/A\",\n",
    "                \"Status\": f\"Error: {str(e)[:40]}\",\n",
    "            })\n",
    "\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "print(\"Error Analysis: Challenging Inputs\")\n",
    "analyze_failure_modes()"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "**Observations**: SpeechT5 handles standard English text well but may struggle with abbreviations, special characters, and non-English text. Numbers are typically spelled out by the model. For production use, text normalization (expanding abbreviations, converting numbers to words) improves quality.\n",
    "\n",
    "## State-of-the-Art TTS Models"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "sota_df = pd.DataFrame([\n",
    "    {\"Model\": \"SpeechT5\", \"Size\": \"200MB\", \"Languages\": \"English\", \"Voice Cloning\": \"No\", \"Best For\": \"Learning, simple TTS\"},\n",
    "    {\"Model\": \"Bark (Suno)\", \"Size\": \"~5GB\", \"Languages\": \"Multi\", \"Voice Cloning\": \"Yes\", \"Best For\": \"Expressive, multilingual\"},\n",
    "    {\"Model\": \"XTTS v2 (Coqui)\", \"Size\": \"~2GB\", \"Languages\": \"17\", \"Voice Cloning\": \"Yes\", \"Best For\": \"Voice cloning, production\"},\n",
    "    {\"Model\": \"VITS\", \"Size\": \"~150MB\", \"Languages\": \"Varies\", \"Voice Cloning\": \"No\", \"Best For\": \"Fast, lightweight TTS\"},\n",
    "    {\"Model\": \"Tortoise TTS\", \"Size\": \"~4GB\", \"Languages\": \"English\", \"Voice Cloning\": \"Yes\", \"Best For\": \"Highest quality, slow\"},\n",
    "])\n",
    "\n",
    "print(\"TTS Model Landscape\")\n",
    "sota_df"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Exercises\n",
    "\n",
    "1. **Long Text**: Generate speech for a full paragraph (100+ words). Use the `synthesize_long_text` function.\n",
    "\n",
    "2. **Voice Comparison**: Try 10 different speaker embedding indices and find the voice you prefer.\n",
    "\n",
    "3. **Punctuation Effect**: Compare audio for the same sentence with different punctuation (period, question mark, exclamation, ellipsis).\n",
    "\n",
    "4. **Audio Analysis**: Plot the mel-spectrogram of generated speech using `librosa` or `torchaudio`.\n",
    "\n",
    "5. **Round-trip Test**: Generate speech from text, then use Notebook 07 (Whisper) to transcribe it back. How much text is preserved?"
  ]},
  {"cell_type": "markdown", "metadata": {}, "source": [
    "## Key Takeaways\n",
    "\n",
    "- **SpeechT5** generates natural-sounding English speech from text\n",
    "- The pipeline has three components: text encoder, speech decoder, and vocoder (HiFi-GAN)\n",
    "- **Speaker embeddings** control voice characteristics -- swap embeddings to change voices\n",
    "- Generated audio is 16kHz WAV format, suitable for most applications\n",
    "- For long text, split into sentences and concatenate with silence gaps\n",
    "- SpeechT5 is English-focused; for multilingual TTS, consider Bark or XTTS v2\n",
    "\n",
    "## Next Steps & Resources\n",
    "\n",
    "**Next Notebook**: Notebook 09 -- Image-to-Text with BLIP\n",
    "\n",
    "**Documentation**:\n",
    "- [SpeechT5 Paper](https://arxiv.org/abs/2110.07205)\n",
    "- [HuggingFace SpeechT5 Guide](https://huggingface.co/docs/transformers/model_doc/speecht5)\n",
    "- [HiFi-GAN Paper](https://arxiv.org/abs/2010.05646)\n",
    "- [CMU Arctic Dataset](http://www.festvox.org/cmu_arctic/)"
  ]}
 ],
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.0"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('notebooks/03_audio/08_audio_text_to_speech.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

md = sum(1 for c in nb['cells'] if c['cell_type'] == 'markdown')
code = sum(1 for c in nb['cells'] if c['cell_type'] == 'code')
total = len(nb['cells'])
print(f'Written: {total} cells ({md} markdown, {code} code, {100*md/total:.0f}% md)')
